v1.1.0
ministryofjustice/analytical-platform pull request #1134
Opened 2023-08-10 15:31 UTC by LavMatt

These changes improve schema inference of a csv, with much improved type inference. 

Also includes the new base image and custom logger functionality.

2023-08-14 09:19 UTC, murdo-moj commented on containers/daap-athena-load/CHANGELOG.md
> +## [1.1.0]
is there logic to how we're incrementing versions?

2023-08-16 08:43 UTC, jacobwoffenden commented on containers/daap-athena-load/CHANGELOG.md
> +- Uses new base image daap-python-base:0.1.0, which includes intial version of the
```suggestion
- Uses new base image daap-python-base:0.3.0, which includes intial version of the
```

2023-08-16 08:43 UTC, jacobwoffenden requested changes
just a minor amendment to the changelog

2023-08-16 08:46 UTC, jacobwoffenden approved these changes

2023-08-16 10:40 UTC, murdo-moj approved these changes

2023-08-16 10:45 UTC, merged