♻️ Refactor Issue Templates
ministryofjustice/analytical-platform pull request #1252
Opened 2023-08-22 13:28 UTC by Gary-H9

This PR refactors the Issue Templates to be more user friendly.

## Before
![Screenshot 2023-08-22 at 14 20 50](https://github.com/ministryofjustice/data-platform/assets/26419401/86257b37-a64d-47d4-8bc3-bde57bec9514)

## After
![Screenshot 2023-08-22 at 14 20 19](https://github.com/ministryofjustice/data-platform/assets/26419401/6b7fdfda-0f2d-4491-b3bb-e5325dc4cfe9)

[Example](https://github.com/ministryofjustice/nvvs-devops/issues/new?assignees=&labels=bug&projects=&template=bug-report.yml&title=%F0%9F%90%9B+%3Ctitle%3E).

Technically this feature is in [Beta](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms) but its in use elsewhere in the organisation and can easily be reverted if required in future.

2023-08-22 14:43 UTC, julialawrence approved these changes, later dismissed
LGTM

2023-08-22 15:21 UTC, bagg3rs approved these changes, later dismissed

2023-08-23 08:13 UTC, julialawrence requested changes
Love the new templates but we need to keep the old ones too.

2023-08-23 08:13 UTC, julialawrence commented on .github/ISSUE_TEMPLATE/bug-template.md
> ----
Can we readd the existing templates with zenhub prefix so people can still use markdown if they'd like and that they can be used on zenhub for those who like to create issues there please?

2023-08-31 10:24 UTC, julialawrence approved these changes
LGTM

2023-08-31 10:26 UTC, merged

2023-08-31 10:27 UTC, jacobwoffenden approved these changes
<img src="https://media4.giphy.com/media/j5vOin8UxCTGluVeMJ/giphy.gif"/>