Update Data as a Product page
ministryofjustice/analytical-platform pull request #1691
Opened 2023-09-27 14:03 UTC by tom-webber

Refresh the Data as a Product page with the current state of the process.
- Add API overview and vision
- replace architecture and data-flow diagrams

resolves #1256

2023-09-27 14:26 UTC, MatMoore approved these changes, later dismissed
Looks really good, and those diagrams look accurate to me. How do we access the source for the pngs if we need to edit them? Are you able to link this in the readme?

2023-09-27 14:26 UTC, MatMoore commented on docs/source/documentation/platform/infrastructure/run-data-product-in-platform.html.md.erb
> +Each Data Product will require a [specification](https://github.com/ministryofjustice/data-platform-products/blob/main/data-products/_docs/product-specification.md) (still under refinement) alongside
Is this up to date? I haven't seen any of these yaml files before, just the example metadata file (a single JSON)

2023-09-27 14:26 UTC, MatMoore commented on docs/source/documentation/platform/infrastructure/run-data-product-in-platform.html.md.erb
> +Data Products:
Maybe this para can be moved further up - it makes sense to define what we mean by a data product before talking about what the API does

2023-09-27 14:26 UTC, MatMoore commented on docs/source/documentation/platform/infrastructure/run-data-product-in-platform.html.md.erb
> +* Are controlled and updated by Data Owners, Data Stewards, and Data Custodians.
These terms should definitely be defined on first use (I'm not sure of the exact meanings myself, and they aren't defined in our [team glossary](https://docs.google.com/spreadsheets/d/1O1EjO96lyqDbyuzFWU8SNBky3b7tKM8dccZVS7-_t9g/edit#gid=1105700365))

2023-09-27 14:26 UTC, MatMoore commented on docs/source/documentation/platform/infrastructure/run-data-product-in-platform.html.md.erb
> +As part of the data flow, Data Product metadata must be passed as part of the request to register or amend a Data Product.
```suggestion
As part of the request to register or amend a Data Product, the API user must provide Data Product metadata.
```

2023-09-27 14:26 UTC, MatMoore commented on docs/source/documentation/platform/infrastructure/run-data-product-in-platform.html.md.erb
> +
Who is the audience for this section? Is it for the team or wider stakeholders? I'm just wondering this duplicating info that should live in the epics/roadmap?

2023-09-27 14:39 UTC, tom-webber commented
> How do we access the source for the pngs if we need to edit them? Are you able to link this in the readme?
I can put the excalidraw json source in the images folder. Might need a reference somewhere in a CONTRIBUTING file to clarify this (not 100% sure where this should go)

2023-09-27 14:40 UTC, tom-webber commented on docs/source/documentation/platform/infrastructure/run-data-product-in-platform.html.md.erb
> +Each Data Product will require a [specification](https://github.com/ministryofjustice/data-platform-products/blob/main/data-products/_docs/product-specification.md) (still under refinement) alongside
I'm not sure. @jemnery do we know what the integration is/should be around the API and these specifications?

2023-09-27 14:47 UTC, bagg3rs commented
> > How do we access the source for the pngs if we need to edit them? Are you able to link this in the readme?
> 
> I can put the excalidraw json source in the images folder. Might need a reference somewhere in a CONTRIBUTING file to clarify this (not 100% sure where this should go)

Just add a `.png` to the `.excalidraw` file and you can edit them via vscode with extension or with excali web. 
https://technical-documentation.data-platform.service.justice.gov.uk/documentation/diagrams/architecture-diagrams.html#contributing-and-updating

2023-09-28 09:02 UTC, tom-webber commented on docs/source/documentation/platform/infrastructure/run-data-product-in-platform.html.md.erb
> +* Are controlled and updated by Data Owners, Data Stewards, and Data Custodians.
@jemnery whereabouts can I find references to what we mean in Data Platform by these terms?

2023-09-28 09:04 UTC, tom-webber commented on docs/source/documentation/platform/infrastructure/run-data-product-in-platform.html.md.erb
> +
Removed - now this only resides in the internal version of this document (on confluence)

2023-09-28 09:20 UTC, jemnery commented on docs/source/documentation/platform/infrastructure/run-data-product-in-platform.html.md.erb
> +* Are controlled and updated by Data Owners, Data Stewards, and Data Custodians.
Suggest just "**Are controlled and updated by Data Owners**" for now, as you're right, I'm fairly sure we haven't defined the Data Steward and Data Custodian roles. In fact those definition's are really up to the DIP team, so let's not create a blocker waiting for those.

2023-09-28 09:23 UTC, jemnery commented on docs/source/documentation/platform/infrastructure/run-data-product-in-platform.html.md.erb
> +> Implementation: The architecture will be built in the `data-platform-development` aws account, a sandbox account within [MoJ's Modernisation Platform](https://user-guide.modernisation-platform.serv
Let's not be environment-specific here (sandbox). Suggest something like:

The architecture will be built in the Data Platform's [Modernisation Platform](https://user-guide.modernisation-platform.service.justice.gov.uk/#modernisation-platform) [environment(s)](https://github.com/ministryofjustice/modernisation-platform-environments/tree/main/terraform/environments/data-platform)

2023-09-28 09:33 UTC, jemnery commented on docs/source/documentation/platform/infrastructure/run-data-product-in-platform.html.md.erb
> +* Are controlled and updated by Data Owners, Data Stewards, and Data Custodians.
You're right, I'm fairly sure we haven't defined the Data Steward and Data Custodian roles. In fact those definitions are really up to the DIP team, so let's not create a blocker waiting for those. There's a suggested edit in the diff.

2023-09-28 09:45 UTC, jemnery commented on docs/source/documentation/platform/infrastructure/run-data-product-in-platform.html.md.erb
> +Each Data Product will require a [specification](https://github.com/ministryofjustice/data-platform-products/blob/main/data-products/_docs/product-specification.md) (still under refinement) alongside
Those YAML specs are still valid in that they contain a decent hypothesis of what metadata we want to capture, but they date from a while back when we thought data product creation could be raising a PR against the "products" repo (like creating a Cloud Platform namespace). So ignore the format, just take it as warning the metadata specs will evolve from here.

2023-09-28 09:50 UTC, jemnery commented on docs/source/documentation/platform/infrastructure/run-data-product-in-platform.html.md.erb
> +API gateway is used to start the data ingestion process.
API Gateway is used to host and manage our API endpoints, so a user will interact with the API to initiate the product registration and data ingestion processes.

2023-09-28 09:51 UTC, jemnery commented on docs/source/documentation/platform/infrastructure/run-data-product-in-platform.html.md.erb
> +#### Reporting tool
I suggest deleting the "Reporting Tool" section from here as it's not adding much and not really relevant to product creation / data ingestion

2023-09-28 09:56 UTC, jemnery requested changes
4 minor edit suggestions inline

2023-09-28 11:02 UTC, jemnery approved these changes

2023-09-28 11:47 UTC, merged