reorder app migration list to reflect app migration batches
ministryofjustice/analytical-platform pull request #229
Opened 2023-03-21 18:06 UTC by tom-webber

## What changed
The ap_migration_apps json list was converted to yaml to allow for apps to be commented out and the 'whole' list used for the map used in the locals, rather than slices.
(judicial reviews paused until manual repo is removed) linting and formatting

## Why?
This allows us to finely control the creation of app repos as we process the batches of apps during the migration

2023-03-21 18:39 UTC, julialawrence requested changes
?

2023-03-21 18:39 UTC, julialawrence commented on terraform/github/ap_migration_apps.yml
Why are we switching to yaml when JSON works?

2023-03-21 18:41 UTC, julialawrence commented on terraform/github/ap_migration_apps.yml
We have the benefit via the magic of source control to recall the parts of the JSON file we remove that doesn't contain the tranche 1 apps. We have a fair bit of work still outstanding before the migration in less than 2 weeks and I am wondering if maybe we shouldn't focus effort on things that work. Please feel free to disagree. 🙂

2023-03-22 08:44 UTC, tom-webber commented on terraform/github/ap_migration_apps.yml
As far as I understand, the output map from the json or from the yaml are the same. The change was purely to allow commenting out items in the file.
I do not mind which format we use to store the data.

2023-03-22 17:14 UTC, bogdan-mania-moj approved these changes, later dismissed

2023-03-22 18:06 UTC, julialawrence approved these changes
Looks good.

2023-03-22 18:17 UTC, jacobwoffenden approved these changes

2023-03-22 18:56 UTC, merged