📝 Add ADR-005 Use AWS Secrets Manager for Secrets
ministryofjustice/analytical-platform pull request #380
Opened 2023-04-28 15:59 UTC by bagg3rs

This PR updates #108 and adds ADR-005 for using AWS Secrets Manager for Secrets

2023-04-28 20:52 UTC, jacobwoffenden submitted a review, later dismissed

2023-05-02 16:10 UTC, jacobwoffenden approved these changes, later dismissed

2023-05-02 16:17 UTC, julialawrence requested changes
Just a bit of rationale for SM vs PS.

2023-05-02 16:17 UTC, julialawrence commented on docs/source/documentation/adrs/adr-005-use-aws-secrets-manager-for-secrets.html.md.erb
> +* All secrets will be stored in Secrets Manager
Would it be possible to articulate what advantage in terms of keeping secret info secret does SM have over PS?

2023-05-05 15:21 UTC, julialawrence approved these changes, later dismissed

2023-05-05 15:25 UTC, julialawrence approved these changes
👍

2023-05-05 15:25 UTC, merged