:wrench: Create Ingestion Issue workflow
ministryofjustice/analytical-platform pull request #5191
Opened 2024-08-28 15:13 UTC by Gary-H9

2024-08-28 15:29 UTC, jacobwoffenden requested changes, later dismissed

2024-08-28 15:29 UTC, jacobwoffenden commented on .github/workflows/ingestion-issue-schedule.yml
> +name: 📥 Create Ingestion Maintenance Patching Issue
```suggestion
---
name: 📥 Create Ingestion Maintenance Patching Issue
```

2024-08-28 15:29 UTC, jacobwoffenden commented on .github/workflows/ingestion-issue-schedule.yml
> +    - cron: 0 8 1,15 * * # UTC time: “At 08:00 on day-of-month 1 and 15.”
```suggestion

on:
  schedule:
    - cron: "0 8 1,15 * *" # UTC time: “At 08:00 on day-of-month 1 and 15.”
    
permissions: {}
```

2024-08-28 15:29 UTC, jacobwoffenden commented on .github/workflows/ingestion-issue-schedule.yml
> +  create_issue:
```suggestion
  create-issue:
```

2024-08-28 15:29 UTC, jacobwoffenden commented on .github/workflows/ingestion-issue-schedule.yml
> +      - name: Create Patching Issue
```suggestion
      - name: Create Patching Issue
        id: create_issue
```

2024-08-28 15:29 UTC, jacobwoffenden commented on .github/workflows/ingestion-issue-schedule.yml
> +          if [[ $CLOSE_PREVIOUS == true ]]; then
```suggestion
          if [[ "${CLOSE_PREVIOUS}" == true ]]; then
```

2024-09-03 07:45 UTC, jamesstottmoj approved these changes
LGTM

2024-09-03 07:51 UTC, merged