feat: migrated CaDeT data bucket from pulumi into terraform
ministryofjustice/analytical-platform pull request #5644
Opened 2024-10-11 11:24 UTC by tom-webber

[CaDeT data bucket](https://github.com/ministryofjustice/create-a-derived-table-infrastructure/blob/e58b7c512add0f25fc95c390089947294714e107/create_a_derived_table_infra/__main__.py#L126) put into data-engineering-pipelines as terraform

Co-authored-by: Ant Fitzroy <AntFMoJ@users.noreply.github.com>

# Pull Request Objective

This piece of work is being tracked in
[this](https://github.com/ministryofjustice/analytical-platform/issues/<your_issue_number_here>)
GitHub Issue.

## Checklist

> [!NOTE]
> Each items should be checked. Skipping below checks could delay your PR review!

- [ ] I have reviewed the [style guide](https://docs.analytical-platform.service.justice.gov.uk/documentation/platform/infrastructure/terraform.html#terraform)
and ensured that my code complies with it
- [ ] All checks have passed (or override label applied, if I've
used the `override-static-analysis` label, I've explained why)
- [ ] I have self-reviewed my code
- [ ] I have reviewed the checks and can attest they're as expected

### Additional Comments

2024-10-14 10:43 UTC, jhpyke requested changes, later dismissed
Can you put an [import block](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket#import) in place for the existing resource so we can see if the plan would lead to divergence from the current state of the bucket? Don't use the CLI import as that'll lock the state, just the inline one.

2024-10-15 14:06 UTC, jacobwoffenden reviewed
Couple of naming things, also I can see changes to components outside of this, like the production cluster, is that the result of a weird merge commit? can this be rebased?

2024-10-15 14:06 UTC, jacobwoffenden commented on terraform/aws/analytical-platform-data-production/create-a-derived-table/terraform.tfvars
> +  application            = "Data Platform"
```suggestion
  application            = "Analytical Platform"
```

2024-10-15 14:06 UTC, jacobwoffenden commented on terraform/aws/analytical-platform-data-production/create-a-derived-table/terraform.tfvars
> +  source-code            = "github.com/ministryofjustice/data-platform/terraform/aws/analytical-platform-data-production/create-a-derived-table"
```suggestion
  owner                  = "analytical-platform:analytical-platformdigital.justice.gov.uk"
  infrastructure-support = "analytical-platform:analytical-platform@digital.justice.gov.uk"
  source-code            = "github.com/ministryofjustice/analytical-platform/terraform/aws/analytical-platform-data-production/create-a-derived-table"
```

2024-10-17 09:23 UTC, jhpyke approved these changes
Looking good to me

2024-10-17 12:18 UTC, merged