Add IAM role and create Glue Crawler task
ministryofjustice/analytical-platform pull request #790
Opened 2023-07-06 12:24 UTC by lalithanagarur

Creating IAM role to assume for Glue Crawler task
Creating policy to allow access S3 bucket and access kms key to decrypt S3 objects
Attached policies and AWS managed GlueServiceRole policy to role
Creating glue database
Creating glue crawler task

2023-07-06 16:02 UTC, jacobwoffenden requested changes

2023-07-06 16:02 UTC, jacobwoffenden commented on .github/workflows/terraform-aws-analytical-platform-data-production-rds-s3-exports copy.yml
would imagine you didn't want to commit this?

2023-07-06 16:02 UTC, jacobwoffenden commented on terraform/aws/analytical-platform-data-production/s3-glue-crawler/glue-catalog.tf
> +resource "aws_glue_catalog_database" "alpha_vcms_data_glue_catalog" {
```suggestion
resource "aws_glue_catalog_database" "alpha_vcms_data" {
```
Don't need to specify resource type in name

2023-07-06 16:02 UTC, jacobwoffenden commented on terraform/aws/analytical-platform-data-production/s3-glue-crawler/glue-crawler.tf
> +  name          = "vcms-data-crawler"
update name and resource name to be use alpha prefix, drop `crawler` from resource name
```suggestion
resource "aws_glue_crawler" "alpha_vmcs_data" {
  database_name = aws_glue_catalog_database.alpha_vcms_data_glue_catalog.name
  name          = "alpha-vcms-data"
```

2023-07-06 16:02 UTC, jacobwoffenden commented on terraform/aws/analytical-platform-data-production/s3-glue-crawler/iam-policies.tf
> +data "aws_iam_policy_document" "crawler_policy" {
```suggestion
data "aws_iam_policy_document" "alpha_vcms_data_crawler_policy" {
```

this needs scoping, incase we want to deploy more crawlers

2023-07-06 16:02 UTC, jacobwoffenden commented on terraform/aws/analytical-platform-data-production/s3-glue-crawler/iam-policies.tf
> +    ]
```suggestion
    resources = ["arn:aws:s3:::alpha-vcms-data/*"]
```

2023-07-06 16:02 UTC, jacobwoffenden commented on terraform/aws/analytical-platform-data-production/s3-glue-crawler/iam-policies.tf
> +    ]
```suggestion
    actions = ["kms:Decrypt"]
```

2023-07-06 16:02 UTC, jacobwoffenden commented on terraform/aws/analytical-platform-data-production/s3-glue-crawler/iam-policies.tf
> +  name   = "vcms-crawler-policy"
```suggestion
resource "aws_iam_policy" "alpha_vcms_data_crawler" {
  name   = "alpha-vcms-data-crawler"
```

2023-07-06 16:02 UTC, jacobwoffenden commented on terraform/aws/analytical-platform-data-production/s3-glue-crawler/iam-role-policy-attachments.tf
> +resource "aws_iam_role_policy_attachment" "vcms_crawler_policy" {
```suggestion
resource "aws_iam_role_policy_attachment" "alpha_vcms_data_crawler" {
```

2023-07-06 16:02 UTC, jacobwoffenden commented on terraform/aws/analytical-platform-data-production/s3-glue-crawler/iam-roles.tf
> +data "aws_iam_policy_document" "glue_policy" {
```suggestion
data "aws_iam_policy_document" "glue_assume_role_policy" {
```

2023-07-06 16:02 UTC, jacobwoffenden commented on terraform/aws/analytical-platform-data-production/s3-glue-crawler/iam-roles.tf
> +  name               = "AWSGlueServiceRole-vcms-crawler"
```suggestion
resource "aws_iam_role" "alpha_vcms_data_crawler" {
  name               = "alpha-vcms-data-crawler"
```

2023-07-06 16:02 UTC, jacobwoffenden commented on terraform/aws/analytical-platform-data-production/s3-glue-crawler/kms-keys.tf
> +}
move to data.tf

2023-07-07 08:34 UTC, lalithanagarur commented on .github/workflows/terraform-aws-analytical-platform-data-production-rds-s3-exports copy.yml
Yep, removed the 'copy' from the name.

2023-07-07 10:06 UTC, jacobwoffenden requested changes

2023-07-07 10:06 UTC, jacobwoffenden commented on terraform/aws/analytical-platform-data-production/s3-glue-crawler/iam-policies.tf
> +  name   = "alpha-vcms-crawler-policy"
```suggestion
  name   = "alpha-vcms-crawler"
```

2023-07-07 10:06 UTC, jacobwoffenden commented on terraform/aws/analytical-platform-data-production/s3-glue-crawler/iam-roles.tf
> +}
```suggestion
resource "aws_iam_role" "alpha_vcms_data_crawler" {
  name                = "alpha-vcms-data-crawler"
  assume_role_policy  = data.aws_iam_policy_document.glue_assume_policy.json
  managed_policy_arns = [
    aws_iam_policy.alpha_vcms_crawler_policy.arn,
    "arn:aws:iam::aws:policy/AWSGlueServiceRole"
  ]
}
```

2023-07-07 10:06 UTC, jacobwoffenden commented on terraform/aws/analytical-platform-data-production/s3-glue-crawler/iam-role-policy-attachments.tf
Can these in favour of the `managed_policy_arns` suggestion on `aws_iam_role.alpha_vcms_data_crawler`

2023-07-07 12:33 UTC, jacobwoffenden approved these changes
approved, but I'll need another @ministryofjustice/data-platform-core-infra engineer to approve

2023-07-07 14:08 UTC, julialawrence approved these changes

2023-07-07 14:10 UTC, merged