enable alert_manager
ministryofjustice/analytical-platform pull request #816
Opened 2023-07-10 08:31 UTC by Emterry

enabling alert_manager to connect to pagerduty services

2023-07-10 11:11 UTC, julialawrence requested changes
Looks good. Two small questions.

2023-07-10 11:11 UTC, julialawrence commented on terraform/pagerduty/modules/service/technical/main.tf
> +  name = "Prometheus"
Should this be `Alert Manager` or do you expect we'll need a separate integration for each source that feeds alerts into the manager?

2023-07-10 11:11 UTC, julialawrence commented on terraform/pagerduty/modules/service/technical/main.tf
> +  #vendor = data.pagerduty_vendor.alert_manager.id
Could you please annotate why this is currently commented out? We will forget. :)

2023-07-10 11:34 UTC, Emterry commented on terraform/pagerduty/modules/service/technical/main.tf
> +  name = "Prometheus"
when i ran the vendor.sh for pagerduty it doesnt provide alertmanager as a vendor - it only provides the vendor id for prometheus alert manager ( the name it required was just prometheus)

2023-07-10 11:45 UTC, jacobwoffenden requested changes

2023-07-10 11:45 UTC, jacobwoffenden commented on vendor.sh
move to `scripts/pagerduty/list-vendors.sh`

2023-07-10 11:45 UTC, jacobwoffenden commented on terraform/pagerduty/modules/service/technical/main.tf
> +  name       = "${local.secretsmanager_prefix}/alert_manager"
```suggestion
  name       = "${local.secretsmanager_prefix}/alert-manager"
```

2023-07-10 11:45 UTC, jacobwoffenden commented on terraform/pagerduty/technical-services.tf
I would enable it on the compute service, not security

2023-07-10 13:56 UTC, julialawrence submitted a review, later dismissed

2023-07-10 14:35 UTC, jacobwoffenden requested changes
It's still enabled on Analytical Platform Security service

2023-07-11 08:43 UTC, jacobwoffenden approved these changes

2023-07-11 08:51 UTC, merged